apiVersion: v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
        resources:
          limits:
            cpu: "3"
            memory: "3Gi"
          requests:
            cpu: "3"
            memory: "3Gi"
