apiVersion: v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
        resources:
          limits:
            cpu: "300m"
            memory: "300Mi"
          requests:
            cpu: "300m"
            memory: "300Mi"
